---
- name: Set up VyOS Users
  hosts: vyos
  gather_facts: false
  order: inventory
  vars_files:
    - ./vars/users.yml
  roles:
    - vyos_users
  post_tasks:
    - name: "Configure vyos Users"
      vyos.vyos.vyos_config:
        save: true

