---
- name: Set up VyOS firewalls
  hosts: vyos
  gather_facts: false
  order: inventory
  roles:
    - vyos_base
  post_tasks:
    - name: "Configure base vyos"
      vyos.vyos.vyos_config:
        save: true
